# Generated by Django 5.1.2 on 2024-12-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(verbose_name='Пароль'),
        ),
    ]
