# Generated by Django 5.1.2 on 2024-11-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_printing_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
