# Generated by Django 5.1.2 on 2024-11-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('visible', 'Показана'), ('deleted', 'Удалена')], default='visible', max_length=10),
        ),
    ]
