# Generated by Django 5.1.2 on 2024-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjob',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
