# Generated by Django 5.1.2 on 2024-12-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_printingjob_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printingjob',
            old_name='quantity',
            new_name='duration',
        ),
    ]
