# Generated by Django 5.1.1 on 2024-11-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('visible', 'Показана'), ('deleted', 'Удалена')], default='default', max_length=10),
        ),
    ]
