# Generated by Django 5.1.1 on 2024-12-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printingjob',
            old_name='quantity',
            new_name='duration',
        ),
    ]
