# Generated by Django 5.1.1 on 2024-11-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printingjob',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
