# Generated by Django 5.1.1 on 2024-11-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_printingjob_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
